language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9

cache:
  pip: true
  directories:
    - $HOME/.pip-cache

before_install:
  - python -m pip install --upgrade pip
install:
  - pip install -r requirements.txt
script:
  - pytest